
//Actions for Install

export const TAKE_AMOUNT = "TAKE_AMOUNT";
export const CALCULATE_ADVANCE = "CALCULATE_ADVANCE";
export const SELECT_INSTALLMENT = "SELECT_INSTALLMENT";
export const CALCULATE_FINALINSTALLMEMT = "CALCULATE_FINALINSTALLMEMT";
