
//Actions for Install

export const TAKE_AMOUNT = "TAKE_AMOUNT";
export const CALCULATE_ADVANCE = "CALCULATE_ADVANCE";
export const SELECT_INSTALLMENT = "SELECT_INSTALLMENT";
export const CALCULATE_INSTALLMENTVALUES = "CALCULATE_INSTALLMENTVALUES";
export const CALCULATE_FINALINSTALLMENT = "CALCULATE_FINALINSTALLMENT";




//Actions for User 

export const TAKE_NAME = "TAKE_NAME";
export const TAKE_SURNAME = "TAKE_SURNAME";
export const TAKE_TEL = "TAKE_TEL";
export const TAKE_EMAIL = "TAKE_EMAIL";
export const TAKE_CONFIRMEMAIL = "TAKE_CONFIRMEMAIL";
