
//Actions for Install

export const TAKE_AMOUNT = "TAKE_AMOUNT";
export const TAKE_ADVANCE = "CALCULATE_ADVANCE";
export const SELECT_INSTALLMENT = "SELECT_INSTALLMENT";
export const RATA_MENSILE = "RATA_MENSILE";
export const CALCULATE_FINALINSTALLMENT = "CALCULATE_FINALINSTALLMENT";
export const IMPORTO_FINANZIATO = 'IMPORTO_FINANZIATO'
export const COSTI_FINANZIAMENTO = 'COSTI_FINANZIAMENTO'
export const IMPORTO_RIMBORSARE = 'IMPORTO_RIMBORSARE'
export const SPESE_ISTRUTTORIA = 'SPESE_ISTRUTTORIA'
export const SPESA_INCASSO = 'SPESA_INCASSO'
export const IMPOSTA_BOLLO = 'IMPOSTA_BOLLO'
export const TAN = 'TAN'
export const TAEG = 'TAEG'
 

//Actions for User 

export const TAKE_NAME = "TAKE_NAME";
export const TAKE_SURNAME = "TAKE_SURNAME";
export const TAKE_TEL = "TAKE_TEL";
export const TAKE_EMAIL = "TAKE_EMAIL";
export const TAKE_CONFIRMEMAIL = "TAKE_CONFIRMEMAIL";
